name: zen_file_transfer
description: A new way fo File Transfer.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_svg: ^1.1.3
  lottie:
  unicons:
  dio: ^4.0.6
  path_provider: ^2.0.11
  get_it: ^7.2.0
  get:
  path: ^1.8.1
  animated_splash_screen:
  flex_color_scheme:
  url_launcher: ^6.1.5
  page_transition:
  shared_preferences: ^2.0.15
  introduction_screen: ^3.0.2
  flutter_markdown: ^0.6.1
  mailto: ^2.0.0
  responsive_framework:
  receive_sharing_intent: ^1.4.5


  platform: ^3.1.0
  # Flutterfall
  equatable:
  formz:
  flutter_bloc:

  # UI
  linkwell: ^2.0.6
  dynamic_themes: ^1.1.0
  fluttertoast:
  timeago:

  
  http:
  #  file_picker is faster and doesn't cache files unnecessarily(Custom)
  file_picker:
    git:
      url:
        https://github.com/abhi16180/flutter_file_picker.git
  open_file:
    git:
      url: https://github.com/abhi16180/open_file.git
  hive: ^2.2.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#ffffff"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, d


  
  flutter_lints: ^2.0.0
  flutter_distributor:
  build_runner:
  change_app_package_name:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/


  fonts:
    - family:
      fonts:
        - asset: assets/fonts/
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
